#!/bin/sh
if ! uci -q get network.wwan >/dev/null 2>&1; then
    logger -t "l850gl" "uci-defaults: membuat konfigurasi awal"
    uci set network.wwan=interface
    uci set network.wwan.proto='atc'
    uci set network.wwan.apn='internet'
    uci set network.wwan.delay='15'
    uci set network.wwan.metric='10'
    uci set network.wwan.auto='1'
    uci commit network
fi
(sleep 10 && /usr/bin/l850gl-init add) &
exit 0
