#!/bin/sh
#
# Hotplug handler untuk Fibocom L850-GL
# VID:PID = 2cb7:0007
#

case "$ACTION" in
    add|bind)
        case "$PRODUCT" in
            2cb7/0007/*)
                logger -t "l850gl" "Modem L850GL terdeteksi (PRODUCT=$PRODUCT), menjalankan inisialisasi..."
                /usr/bin/l850gl-init add &
                ;;
        esac
        ;;
    remove)
        case "$PRODUCT" in
            2cb7/0007/*)
                logger -t "l850gl" "Modem L850GL dicabut (PRODUCT=$PRODUCT), membersihkan interface..."
                /usr/bin/l850gl-init remove &
                ;;
        esac
        ;;
esac

exit 0
