#!/bin/sh
case "$ACTION" in
    add|bind)
        case "$PRODUCT" in
            8087/095a/*)
                logger -t "l850gl-hotplug" "Modem terdeteksi, menjalankan init"
                /usr/bin/l850gl-init add &
                ;;
        esac
        ;;
    remove)
        case "$PRODUCT" in
            8087/095a/*)
                logger -t "l850gl-hotplug" "Modem dicabut, membersihkan"
                /usr/bin/l850gl-init remove &
                ;;
        esac
        ;;
esac
